# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 3600s
options:
  machineType: "N1_HIGHCPU_32"
  diskSizeGb: "512"

substitutions:
  _USE_CACHE: "true"
  _IMAGE_PREFIX: webrtc-gpu-streaming
  _IMAGE_TAG: latest

tags:
  - selkies-vdi-images

###
# Images to be pushed
###
images: [
    # gst-webrtc-app
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-gst-webrtc-app:${_IMAGE_TAG}',
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-gst-webrtc-app:latest',
    # watchdog
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-watchdog:${_IMAGE_TAG}',
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-watchdog:latest',
    # desktop
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-desktop:${_IMAGE_TAG}',
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-desktop:latest',
    # xserver
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-xserver:${_IMAGE_TAG}',
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-xserver:latest',
    # pulseaudio
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-pulseaudio:${_IMAGE_TAG}',
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-pulseaudio:latest',
    # app-streaming
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:${_IMAGE_TAG}',
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:latest',
    # app-streaming:bionic
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:bionic',
    # app-streaming:focal
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:focal',
    # app-streaming:focal-cuda
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:focal-cuda',
    # xpra
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-xpra:${_IMAGE_TAG}',
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-xpra:latest',
    # squid-proxy
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-squid-proxy:${_IMAGE_TAG}',
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-squid-proxy:latest',
    # tinyfilemanager
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-tinyfilemanager:${_IMAGE_TAG}',
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-tinyfilemanager:latest',
    # uinput-device-plugin
    'gcr.io/${PROJECT_ID}/uinput-device-plugin:${_IMAGE_TAG}',
    'gcr.io/${PROJECT_ID}/uinput-device-plugin:latest',
]

steps:
###
# WebRTC app image
###
- name: 'gcr.io/cloud-builders/docker'
  id: gst-webrtc-app-pull
  entrypoint: 'bash'
  args: ["-c", "if [[ '${_USE_CACHE}' == 'true' ]]; then (docker pull gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-gst-webrtc-app:latest || exit 0); fi"]
  waitFor: ["-"]
- name: 'gcr.io/cloud-builders/docker'
  id: gst-webrtc-app
  args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-gst-webrtc-app:${_IMAGE_TAG}',
            '--cache-from', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-gst-webrtc-app:latest',
            'webrtc'
        ]
  waitFor:
    - gst-webrtc-app-pull
- name: 'gcr.io/cloud-builders/docker'
  id: gst-webrtc-app-tags
  args: [
            'tag',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-gst-webrtc-app:${_IMAGE_TAG}',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-gst-webrtc-app:latest',
        ]
  waitFor:
    - gst-webrtc-app

###
# Watchdog image
###
- name: 'gcr.io/cloud-builders/docker'
  id: watchdog-pull
  entrypoint: 'bash'
  args: ["-c", "if [[ '${_USE_CACHE}' == 'true' ]]; then (docker pull gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-watchdog:latest || exit 0); fi"]
  waitFor: ["-"]
- name: 'gcr.io/cloud-builders/docker'
  id: watchdog
  args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-watchdog:${_IMAGE_TAG}',
            '--cache-from', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-watchdog:latest',
            'watchdog'
        ]
  waitFor:
    - watchdog-pull
- name: 'gcr.io/cloud-builders/docker'
  id: watchdog-tags
  args: [
            'tag',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-watchdog:${_IMAGE_TAG}',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-watchdog:latest',
        ]
  waitFor:
    - watchdog

###
# Desktop image with debian Cloud Shell image as base.
###
- name: 'gcr.io/cloud-builders/docker'
  id: desktop-pull
  entrypoint: 'bash'
  args: ["-c", "if [[ '${_USE_CACHE}' == 'true' ]]; then (docker pull gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-desktop:latest || exit 0); fi"]
  waitFor: ["-"]
- name: 'gcr.io/cloud-builders/docker'
  id: desktop
  args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-desktop:${_IMAGE_TAG}',
            '--cache-from', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-desktop:latest',
            'desktop'
        ]
  waitFor:
    - desktop-pull
- name: 'gcr.io/cloud-builders/docker'
  id: desktop-tags
  args: [
            'tag',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-desktop:${_IMAGE_TAG}',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-desktop:latest',
        ]
  waitFor:
    - desktop

###
# XServer image
###
- name: 'gcr.io/cloud-builders/docker'
  id: xserver-pull
  entrypoint: 'bash'
  args: ["-c", "if [[ '${_USE_CACHE}' == 'true' ]]; then (docker pull gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-xserver:latest || exit 0); fi"]
  waitFor: ["-"]
- name: 'gcr.io/cloud-builders/docker'
  id: xserver
  args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-xserver:${_IMAGE_TAG}',
            '--cache-from', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-xserver:latest',
            'xserver'
        ]
  waitFor:
    - xserver-pull
- name: 'gcr.io/cloud-builders/docker'
  id: xserver-tags
  args: [
            'tag',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-xserver:${_IMAGE_TAG}',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-xserver:latest',
        ]
  waitFor:
    - xserver

###
# Pulseaudio image
###
- name: 'gcr.io/cloud-builders/docker'
  id: pulseaudio-pull
  entrypoint: 'bash'
  args: ["-c", "if [[ '${_USE_CACHE}' == 'true' ]]; then (docker pull gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-pulseaudio:latest || exit 0); fi"]
  waitFor: ["-"]
- name: 'gcr.io/cloud-builders/docker'
  id: pulseaudio
  args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-pulseaudio:${_IMAGE_TAG}',
            '--cache-from', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-pulseaudio:latest',
            'pulseaudio'
        ]
  waitFor:
    - pulseaudio-pull
- name: 'gcr.io/cloud-builders/docker'
  id: pulseaudio-tags
  args: [
            'tag',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-pulseaudio:${_IMAGE_TAG}',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-pulseaudio:latest',
        ]
  waitFor:
    - pulseaudio

###
# App streaming image based on Debian Buster (latest tag)
###
- name: 'gcr.io/cloud-builders/docker'
  id: app-streaming-pull
  entrypoint: 'bash'
  args: ["-c", "if [[ '${_USE_CACHE}' == 'true' ]]; then (docker pull gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:latest || exit 0); fi"]
  waitFor: ["-"]
- name: 'gcr.io/cloud-builders/docker'
  id: app-streaming
  args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:${_IMAGE_TAG}',
            '--cache-from', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:latest',
            'app-streaming'
        ]
  waitFor:
    - app-streaming-pull
- name: 'gcr.io/cloud-builders/docker'
  id: app-streaming-tags
  args: [
            'tag',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:${_IMAGE_TAG}',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:latest',
        ]
  waitFor:
    - app-streaming

###
# App streaming image based on Ubuntu Bionic (bionic tag)
###
- name: 'gcr.io/cloud-builders/docker'
  id: app-streaming-bionic-pull
  entrypoint: 'bash'
  args: ["-c", "if [[ '${_USE_CACHE}' == 'true' ]]; then (docker pull gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:bionic || exit 0); fi"]
  waitFor: ["-"]
- name: 'gcr.io/cloud-builders/docker'
  id: app-streaming-bionic
  args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:bionic',
            '--cache-from', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:bionic',
            '-f', 'app-streaming/Dockerfile.bionic',
            'app-streaming'
        ]
  waitFor:
    - app-streaming-bionic-pull

###
# App streaming image based on Ubuntu Focal (focal tag)
###
- name: 'gcr.io/cloud-builders/docker'
  id: app-streaming-focal-pull
  entrypoint: 'bash'
  args: ["-c", "if [[ '${_USE_CACHE}' == 'true' ]]; then (docker pull gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:focal || exit 0); fi"]
  waitFor: ["-"]
- name: 'gcr.io/cloud-builders/docker'
  id: app-streaming-focal
  args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:focal',
            '--cache-from', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:focal',
            '-f', 'app-streaming/Dockerfile.focal',
            'app-streaming'
        ]
  waitFor:
    - app-streaming-focal-pull

###
# App streaming image based on Ubuntu Focal with CUDA toolkit (focal-cuda tag)
###
- name: 'gcr.io/cloud-builders/docker'
  id: app-streaming-focal-cuda-pull
  entrypoint: 'bash'
  args: ["-c", "if [[ '${_USE_CACHE}' == 'true' ]]; then (docker pull gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:focal-cuda || exit 0); fi"]
  waitFor: ["-"]
- name: 'gcr.io/cloud-builders/docker'
  id: app-streaming-focal-cuda
  args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:focal-cuda',
            '--cache-from', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-app-streaming:focal-cuda',
            '-f', 'app-streaming/Dockerfile.focal-cuda',
            'app-streaming'
        ]
  waitFor:
    - app-streaming-focal-cuda-pull

###
# Xpra image
###
- name: 'gcr.io/cloud-builders/docker'
  id: xpra-pull
  entrypoint: 'bash'
  args: ["-c", "if [[ '${_USE_CACHE}' == 'true' ]]; then (docker pull gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-xpra:latest || exit 0); fi"]
  waitFor: ["-"]
- name: 'gcr.io/cloud-builders/docker'
  id: xpra
  args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-xpra:${_IMAGE_TAG}',
            '--cache-from', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-xpra:latest',
            'xpra'
        ]
  waitFor:
    - xpra-pull
- name: 'gcr.io/cloud-builders/docker'
  id: xpra-tags
  args: [
            'tag',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-xpra:${_IMAGE_TAG}',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-xpra:latest',
        ]
  waitFor:
    - xpra

###
# squid-proxy image
###
- name: 'gcr.io/cloud-builders/docker'
  id: squid-proxy-pull
  entrypoint: 'bash'
  args: ["-c", "if [[ '${_USE_CACHE}' == 'true' ]]; then (docker pull gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-squid-proxy:latest || exit 0); fi"]
  waitFor: ["-"]
- name: 'gcr.io/cloud-builders/docker'
  id: squid-proxy
  args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-squid-proxy:${_IMAGE_TAG}',
            '--cache-from', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-squid-proxy:latest',
            'squid-proxy'
        ]
  waitFor:
    - squid-proxy-pull
- name: 'gcr.io/cloud-builders/docker'
  id: squid-proxy-tags
  args: [
            'tag',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-squid-proxy:${_IMAGE_TAG}',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-squid-proxy:latest',
        ]
  waitFor:
    - squid-proxy

###
# tinyfilemanager image
###
- name: 'gcr.io/cloud-builders/docker'
  id: tinyfilemanager-pull
  entrypoint: 'bash'
  args: ["-c", "if [[ '${_USE_CACHE}' == 'true' ]]; then (docker pull gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-tinyfilemanager:latest || exit 0); fi"]
  waitFor: ["-"]
- name: 'gcr.io/cloud-builders/docker'
  id: tinyfilemanager
  args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-tinyfilemanager:${_IMAGE_TAG}',
            '--cache-from', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-tinyfilemanager:latest',
            'tinyfilemanager'
        ]
  waitFor:
    - tinyfilemanager-pull
- name: 'gcr.io/cloud-builders/docker'
  id: tinyfilemanager-tags
  args: [
            'tag',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-tinyfilemanager:${_IMAGE_TAG}',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-tinyfilemanager:latest',
        ]
  waitFor:
    - tinyfilemanager

###
# uinput device plugin image
###
- name: 'gcr.io/cloud-builders/docker'
  id: uinput-device-plugin-pull
  entrypoint: 'bash'
  args: ["-c", "if [[ '${_USE_CACHE}' == 'true' ]]; then (docker pull gcr.io/${PROJECT_ID}/uinput-device-plugin:latest || exit 0); fi"]
  waitFor: ["-"]
- name: 'gcr.io/cloud-builders/docker'
  id: uinput-device-plugin
  args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/uinput-device-plugin:${_IMAGE_TAG}',
            '--cache-from', 'gcr.io/${PROJECT_ID}/uinput-device-plugin:latest',
            'uinput-device-plugin'
        ]
  waitFor:
    - uinput-device-plugin-pull
- name: 'gcr.io/cloud-builders/docker'
  id: uinput-device-plugin-tags
  args: [
            'tag',
            'gcr.io/${PROJECT_ID}/uinput-device-plugin:${_IMAGE_TAG}',
            'gcr.io/${PROJECT_ID}/uinput-device-plugin:latest',
        ]
  waitFor:
    - uinput-device-plugin