name: Build & publish all images

on:
  push:
    branches:
      - dev
      - master
    paths:
      - ".github/**"
  workflow_dispatch:

env:
  github_token: ${{ secrets.GITHUB_TOKEN }}
  github_username: ${{ github.actor }}
  image_version: ${{ github.ref_name }}

jobs:
  app_proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: app-proxy
          image_source_directory: images/app-proxy
          image_version_1: $image_version

  app_streaming_bionic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          dockerfile: Dockerfile.bionic
          github_token: $github_token
          github_username: $github_username
          image_name: app-streaming
          image_source_directory: images/app-streaming
          image_version_1: $image_version
          image_version_suffix: -bionic

  app_streaming_buster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: app-streaming
          image_source_directory: images/app-streaming
          image_version_1: $image_version
          image_version_suffix: -buster

  app_streaming_focal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          dockerfile: Dockerfile.focal
          github_token: $github_token
          github_username: $github_username
          image_name: app-streaming
          image_source_directory: images/app-streaming
          image_version_1: $image_version
          image_version_suffix: -focal

  app_streaming_focal_cuda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          dockerfile: Dockerfile.focal-cuda
          github_token: $github_token
          github_username: $github_username
          image_name: app-streaming
          image_source_directory: images/app-streaming
          image_version_1: $image_version
          image_version_suffix: -focal-cuda

  desktop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: desktop
          image_source_directory: images/desktop
          image_version_1: $image_version

  pulseaudio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: pulseaudio
          image_source_directory: images/pulseaudio
          image_version_1: $image_version

  squid_proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: squid-proxy
          image_source_directory: images/squid-proxy
          image_version_1: $image_version

  tinyfilemanager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: tinyfilemanager
          image_source_directory: images/tinyfilemanager
          image_version_1: $image_version

  uinput_device_plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: uinput-device-plugin
          image_source_directory: images/uinput-device-plugin
          image_version_1: $image_version

  watchdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: watchdog
          image_source_directory: images/watchdog
          image_version_1: $image_version

  webrtc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: webrtc
          image_source_directory: images/webrtc
          image_version_1: $image_version

  xpra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: xpra
          image_source_directory: images/xpra
          image_version_1: $image_version

  xserver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: xserver
          image_source_directory: images/xserver
          image_version_1: $image_version
