name: Build & publish all images

on:
  workflow_call:
    inputs:
      image_version_1:
        description: A version for all image tags, such as "foo" in "ghcr.io/user/repo/image:foo"
        required: true
        type: string
      image_version_2:
        description: Another version for all image tags, such as "bar" in "ghcr.io/user/repo/image:bar"
        required: false
        type: string

jobs:

  build_and_publish_app_streaming_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/app-streaming
        image_name: webrtc-gpu-streaming-app-streaming
        image_version_1: ${{ inputs.image_version_1 }}
        image_version_2: ${{ inputs.image_version_2 }}

  build_and_publish_app_streaming_bionic_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        dockerfile: Dockerfile.bionic
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/app-streaming
        # TODO: Should we add "bionic" to the name?
        image_name: webrtc-gpu-streaming-app-streaming
        # TODO: Should we have a version history (with "latest")?
        image_version_1: bionic

  build_and_publish_app_streaming_focal_cuda_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        dockerfile: Dockerfile.focal-cuda
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/app-streaming
        # TODO: Should we add "focal-cuda" to the name?
        image_name: webrtc-gpu-streaming-app-streaming
        image_version_1: focal-cuda

  build_and_publish_app_streaming_focal_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        dockerfile: Dockerfile.focal
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/app-streaming
        # TODO: Should we add "focal" to the name?
        image_name: webrtc-gpu-streaming-app-streaming
        image_version_1: focal

  build_and_publish_desktop_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/desktop
        image_name: webrtc-gpu-streaming-desktop
        image_version_1: ${{ inputs.image_version_1 }}
        image_version_2: ${{ inputs.image_version_2 }}

  build_and_publish_pulseaudio_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/pulseaudio
        image_name: webrtc-gpu-streaming-pulseaudio
        image_version_1: ${{ inputs.image_version_1 }}
        image_version_2: ${{ inputs.image_version_2 }}

  build_and_publish_squid_proxy_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/squid-proxy
        image_name: webrtc-gpu-streaming-squid-proxy
        image_version_1: ${{ inputs.image_version_1 }}
        image_version_2: ${{ inputs.image_version_2 }}

  build_and_publish_tinyfilemanager_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/tinyfilemanager
        image_name: webrtc-gpu-streaming-tinyfilemanager
        image_version_1: ${{ inputs.image_version_1 }}
        image_version_2: ${{ inputs.image_version_2 }}

  build_and_publish_uinput_device_plugin_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/uinput-device-plugin
        image_name: uinput-device-plugin
        image_version_1: ${{ inputs.image_version_1 }}
        image_version_2: ${{ inputs.image_version_2 }}

  build_and_publish_watchdog_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/watchdog
        image_name: webrtc-gpu-streaming-watchdog
        image_version_1: ${{ inputs.image_version_1 }}
        image_version_2: ${{ inputs.image_version_2 }}

  build_and_publish_xpra_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/xpra
        image_name: webrtc-gpu-streaming-xpra
        image_version_1: ${{ inputs.image_version_1 }}
        image_version_2: ${{ inputs.image_version_2 }}

  build_and_publish_xserver_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/xserver
        image_name: webrtc-gpu-streaming-xserver
        image_version_1: ${{ inputs.image_version_1 }}
        image_version_2: ${{ inputs.image_version_2 }}

  build_and_publish_webrtc_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/webrtc
        image_name: webrtc-gpu-streaming-gst-webrtc-app
        image_version_1: ${{ inputs.image_version_1 }}
        image_version_2: ${{ inputs.image_version_2 }}
