name: Build & publish all images

on:
  workflow_call:
    inputs:
      image_version_1:
        description: A version for all image tags, such as "foo" in "ghcr.io/user/repo/image:foo"
        required: true
        type: string
      image_version_2:
        description: Another version for all image tags, such as "bar" in "ghcr.io/user/repo/image:bar"
        required: false
        type: string

jobs:

  build_and_publish_TEMPLATE_image:
    needs: get_version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/TEMPLATE
        image_name: TEMPLATE
        image_version_1: ${{ inputs.image_version_1 }}
        image_version_2: ${{ inputs.image_version_2 }}
        use_cache: "true"
