name: Build & publish all images

on: workflow_dispatch

jobs:

  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get.outputs.version }}
    steps:
    - id: get
      run: |
        echo ::set-output name=version::${GITHUB_REF#refs/*/}

  build_and_publish_TEMPLATE_image:
    needs: get_version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/TEMPLATE
        image_tag_1: ghcr.io/selkies-project/selkies-vdi/TEMPLATE:${{ needs.get_version.outputs.version }}
        use_cache: "true"
