name: Build & publish changed images

on:
  push:
    branches:
      - master

jobs:

  ###
  # Get release version from build context
  ###
  release_version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo $RELEASE_VERSION
        echo ${{ steps.vars.outputs.tag }}

  detect_image_source_changes:
    runs-on: ubuntu-latest
    outputs:
      infra_gcp_installer_changed: ${{ steps.changes_to_infra_gcp_installer.outputs.any_changed == 'true' || steps.changes_to_infra_gcp_installer.outputs.any_deleted == 'true' }}
      addons_coturn_changed: ${{ steps.changes_to_addons_coturn.outputs.any_changed == 'true' || steps.changes_to_addons_coturn.outputs.any_deleted == 'true' }}
      addons_coturn-web_changed: ${{ steps.changes_to_addons_coturn-web.outputs.any_changed == 'true' || steps.changes_to_addons_coturn-web.outputs.any_deleted == 'true' }}
      addons_gst-web_changed: ${{ steps.changes_to_addons_gst-web.outputs.any_changed == 'true' || steps.changes_to_addons_gst-web.outputs.any_deleted == 'true' }}
      addons_gstreamer_changed: ${{ steps.changes_to_addons_gstreamer.outputs.any_changed == 'true' || steps.changes_to_addons_gstreamer.outputs.any_deleted == 'true' }}
      py_build_changed: ${{ steps.changes_to_py_build.outputs.any_changed == 'true' || steps.changes_to_py_build.outputs.any_deleted == 'true' }}
      gst_py_test_changed: ${{ steps.changes_to_gst_py_example.outputs.any_changed == 'true' || steps.changes_to_gst_py_example.outputs.any_deleted == 'true' }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2 # This is for changed-files.

    ###
    # Detect changes to infra/gce/installer-image
    ###
    - id: changes_to_infra_gcp_installer
      name: Check for GCP installer changes
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: infra/gce/installer-image
    - run: |
        echo '${{ toJSON(steps.changes_to_infra_gcp_installer) }}'

    ###
    # Detect changes to addons/coturn
    ###
    - id: changes_to_addons_coturn
      name: Check for coTURN changes
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: addons/coturn
    - run: |
        echo '${{ toJSON(steps.changes_to_addons_coturn) }}'

    ###
    # Detect changes to addons/coturn-web
    ###
    - id: changes_to_addons_coturn-web
      name: Check for coTURN web changes
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: addons/coturn-web
    - run: |
        echo '${{ toJSON(steps.changes_to_addons_coturn-web) }}'

    ###
    # Detect changes to addons/gst-web
    ###
    - id: changes_to_addons_gst-web
      name: Check for gst-web changes
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: addons/gst-web
    - run: |
        echo '${{ toJSON(steps.changes_to_addons_gst-web) }}'

    ###
    # Detect changes to addons/gstreamer
    ###
    - id: changes_to_addons_gstreamer
      name: Check for gstreamer changes
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: addons/gstreamer
    - run: |
        echo '${{ toJSON(steps.changes_to_addons_gstreamer) }}'

    ###
    # Detect changes to python build image
    ###
    - id: changes_to_py_build
      name: Check for python dist changes
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: |
          ^src
          ^Dockerfile$
          pyproject.toml
          setup.cfg
          .github/workflows/build_and_publish_changed_images.yaml
    - run: |
        echo '${{ toJSON(steps.changes_to_py_build) }}'
    
    ###
    # Detect changes to example image
    ###
    - id: changes_to_gst_py_example
      name: Check for example changes
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: |
          addons
          src
          Dockerfile
          Dockerfile.example
          pyproject.toml
          setup.cfg
          .github/workflows/build_and_publish_changed_images.yaml
    - run: |
        echo '${{ toJSON(steps.changes_to_gst_py_example) }}'

  ###
  # GCP infrastructure installer image
  ###
  build_infra_gcp_installer:
    needs:
    - release_version
    - detect_image_source_changes
    if: needs.detect_image_source_changes.outputs.infra_gcp_installer_changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        use_cache: "true"
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: infra/gce/installer-image
        image_tag_1: ghcr.io/selkies-project/selkies-gstreamer/infra-gcp-installer:${{ needs.release_version.outputs.tag }}

  ###
  # Coturn image
  ###
  build_addons_coturn:
    needs:
    - release_version
    - detect_image_source_changes
    if: needs.detect_image_source_changes.outputs.addons_coturn_changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        use_cache: "true"
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: addons/coturn
        image_tag_1: ghcr.io/selkies-project/selkies-gstreamer/coturn:${{ needs.release_version.outputs.tag }}

  ###
  # Coturn Web image
  ###
  build_addons_coturn-web:
    needs:
    - release_version
    - detect_image_source_changes
    if: needs.detect_image_source_changes.outputs.addons_coturn-web_changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        use_cache: "true"
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: addons/coturn-web
        image_tag_1: ghcr.io/selkies-project/selkies-gstreamer/coturn-web:${{ needs.release_version.outputs.tag }}

  ###
  # gst-web image
  ###
  build_addons_gst-web:
    needs:
    - release_version
    - detect_image_source_changes
    if: needs.detect_image_source_changes.outputs.addons_gst-web_changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        use_cache: "true"
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: addons/gst-web
        image_tag_1: ghcr.io/selkies-project/selkies-gstreamer/gst-web:${{ needs.release_version.outputs.tag }}

  ###
  # Gstreamer image, ubuntu 18.04
  ###
  build_addons_gstreamer_ubuntu1804:
    needs:
    - release_version
    - detect_image_source_changes
    if: needs.detect_image_source_changes.outputs.addons_gstreamer_changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        use_cache: "true"
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: addons/gstreamer
        image_tag_1: ghcr.io/selkies-project/selkies-gstreamer/gstreamer:${{ needs.release_version.outputs.tag }}-ubuntu18.04
        build_args: BASE_IMAGE=ubuntu:18.04;

  ###
  # Gstreamer image, latest and ubuntu 20.04
  ###
  build_addons_gstreamer_ubuntu2004:
    needs:
    - release_version
    - detect_image_source_changes
    if: needs.detect_image_source_changes.outputs.addons_gstreamer_changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        use_cache: "true"
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: addons/gstreamer
        image_tag_1: ghcr.io/selkies-project/selkies-gstreamer/gstreamer:${{ needs.release_version.outputs.tag }}-ubuntu20.04
        build_args: BASE_IMAGE=ubuntu:20.04;

  ###
  # Python package image
  ###
  build_py_build:
    needs:
    - release_version
    - detect_image_source_changes
    if: needs.detect_image_source_changes.outputs.py_build_changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        use_cache: "true"
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: .
        image_tag_1: ghcr.io/selkies-project/selkies-gstreamer/py-build:${{ needs.release_version.outputs.tag }}
        build_args: PACKAGE_VERSION=0.0.0-dev

  ###
  # Test image, Ubuntu 18.04
  ###
  build_gst-py-example_ubuntu1804:
    needs:
    - release_version
    - detect_image_source_changes
    - build_addons_gst-web
    - build_addons_gstreamer_ubuntu1804
    - build_py_build
    if: always()
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        use_cache: "true"
        dockerfile: Dockerfile.example
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: .
        image_tag_1: ghcr.io/selkies-project/selkies-gstreamer/gst-py-example:${{ needs.release_version.outputs.tag }}-ubuntu18.04
        build_args: PACKAGE_VERSION=0.0.0.dev0;UBUNTU_RELEASE=18.04;GSTREAMER_BASE_IMAGE_RELEASE=${{ needs.release_version.outputs.tag }};PY_BUILD_IMAGE=ghcr.io/selkies-project/selkies-gstreamer/py-build:${{ needs.release_version.outputs.tag }};WEB_IMAGE=ghcr.io/selkies-project/selkies-gstreamer/gst-web:${{ needs.release_version.outputs.tag }}

  ###
  # Test image, Ubuntu 20.04
  ###
  build_gst-py-example_ubuntu2004:
    needs:
    - release_version
    - detect_image_source_changes
    - build_addons_gst-web
    - build_addons_gstreamer_ubuntu2004
    - build_py_build
    if: always()
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        use_cache: "true"
        dockerfile: Dockerfile.example
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: .
        image_tag_1: ghcr.io/selkies-project/selkies-gstreamer/gst-py-example:${{ needs.release_version.outputs.tag }}
        build_args: PACKAGE_VERSION=0.0.0.dev0;UBUNTU_RELEASE=20.04;GSTREAMER_BASE_IMAGE_RELEASE=${{ needs.release_version.outputs.tag }};PY_BUILD_IMAGE=ghcr.io/selkies-project/selkies-gstreamer/py-build:${{ needs.release_version.outputs.tag }};WEB_IMAGE=ghcr.io/selkies-project/selkies-gstreamer/gst-web:${{ needs.release_version.outputs.tag }}
