name: Build & publish changed images

on:
  workflow_call:
    inputs:
      image_version:
        description: A version for all image tags, such as "foo" in "ghcr.io/user/repo/image:foo"
        required: true
        type: string

jobs:

  detect_image_source_changes:
    runs-on: ubuntu-latest
    outputs:
      desktop_changed: ${{ steps.check_desktop.outputs.any_changed == 'true' || steps.check_desktop.outputs.any_deleted == 'true' }}
      pulseaudio_changed: ${{ steps.check_pulseaudio.outputs.any_changed == 'true' || steps.check_pulseaudio.outputs.any_deleted == 'true' }}
      squid_proxy_changed: ${{ steps.check_squid_proxy.outputs.any_changed == 'true' || steps.check_squid_proxy.outputs.any_deleted == 'true' }}
      tinyfilemanager_changed: ${{ steps.check_tinyfilemanager.outputs.any_changed == 'true' || steps.check_tinyfilemanager.outputs.any_deleted == 'true' }}
      uinput_device_plugin_changed: ${{ steps.check_uinput_device_plugin.outputs.any_changed == 'true' || steps.check_uinput_device_plugin.outputs.any_deleted == 'true' }}
      watchdog_changed: ${{ steps.check_watchdog.outputs.any_changed == 'true' || steps.check_watchdog.outputs.any_deleted == 'true' }}
      webrtc_changed: ${{ steps.check_webrtc.outputs.any_changed == 'true' || steps.check_webrtc.outputs.any_deleted == 'true' }}
      xpra_changed: ${{ steps.check_xpra.outputs.any_changed == 'true' || steps.check_xpra.outputs.any_deleted == 'true' }}
      xserver_changed: ${{ steps.check_xserver.outputs.any_changed == 'true' || steps.check_xserver.outputs.any_deleted == 'true' }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2 # This is for changed-files.

    - id: check_desktop
      name: Check for changes to the desktop image source
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: images/desktop

    - id: check_pulseaudio
      name: Check for changes to the pulseaudio image source
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: images/pulseaudio

    - id: check_squid_proxy
      name: Check for changes to the squid proxy image source
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: images/squid-proxy

    - id: check_tinyfilemanager
      name: Check for changes to the tinyfilemanager image source
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: images/tinyfilemanager

    - id: check_uinput_device_plugin
      name: Check for changes to the uinput device plugin image source
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: images/uinput-device-plugin

    - id: check_watchdog
      name: Check for changes to the watchdog image source
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: images/watchdog

    - id: check_webrtc
      name: Check for changes to the webrtc image source
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: images/webrtc

    - id: check_xpra
      name: Check for changes to the xpra image source
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: images/xpra

    - id: check_xserver
      name: Check for changes to the xserver image source
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: images/xserver

  build_and_publish_desktop_image_if_changed:
    needs: detect_image_source_changes
    if: needs.detect_image_source_changes.outputs.desktop_changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/desktop
        image_name: webrtc-gpu-streaming-gst-desktop
        image_version_1: ${{ inputs.image_version }}

  build_and_publish_pulseaudio_image_if_changed:
    needs: detect_image_source_changes
    if: needs.detect_image_source_changes.outputs.pulseaudio_changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/pulseaudio
        image_name: webrtc-gpu-streaming-gst-pulseaudio
        image_version_1: ${{ inputs.image_version }}

  build_and_publish_squid_proxy_image_if_changed:
    needs: detect_image_source_changes
    if: needs.detect_image_source_changes.outputs.squid_proxy_changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/squid-proxy
        image_name: webrtc-gpu-streaming-gst-squid-proxy
        image_version_1: ${{ inputs.image_version }}

  build_and_publish_tinyfilemanager_image_if_changed:
    needs: detect_image_source_changes
    if: needs.detect_image_source_changes.outputs.tinyfilemanager_changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/tinyfilemanager
        image_name: webrtc-gpu-streaming-gst-tinyfilemanager
        image_version_1: ${{ inputs.image_version }}

  build_and_publish_uinput_device_plugin_image_if_changed:
    needs: detect_image_source_changes
    if: needs.detect_image_source_changes.outputs.uinput_device_plugin_changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/uinput-device-plugin
        image_name: uinput-device-plugin
        image_version_1: ${{ inputs.image_version }}

  build_and_publish_watchdog_image_if_changed:
    needs: detect_image_source_changes
    if: needs.detect_image_source_changes.outputs.watchdog_changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/watchdog
        image_name: webrtc-gpu-streaming-gst-watchdog
        image_version_1: ${{ inputs.image_version }}

  build_and_publish_webrtc_image_if_changed:
    needs: detect_image_source_changes
    if: needs.detect_image_source_changes.outputs.webrtc_changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/webrtc
        image_name: webrtc-gpu-streaming-gst-webrtc-app
        image_version_1: ${{ inputs.image_version }}

  build_and_publish_xpra_image_if_changed:
    needs: detect_image_source_changes
    if: needs.detect_image_source_changes.outputs.xpra_changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/xpra
        image_name: webrtc-gpu-streaming-gst-xpra
        image_version_1: ${{ inputs.image_version }}

  build_and_publish_xserver_image_if_changed:
    needs: detect_image_source_changes
    if: needs.detect_image_source_changes.outputs.xserver_changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build_and_publish_image
      with:
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        github_username: ${{ github.actor }}
        image_source_directory: images/xserver
        image_name: webrtc-gpu-streaming-gst-xserver
        image_version_1: ${{ inputs.image_version }}
