name: Create a release

on: workflow_call

jobs:

  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get.outputs.version }}
    steps:
    - id: get
      run: |
        echo ::set-output name=version::${GITHUB_REF#refs/*/}

  create_release:
    needs: build_and_publish_all_images
    runs-on: ubuntu-latest
    steps:
    - id: create
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: false
        release_name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
