name: "Trigger: Automation logic was changed on master"

on:
  push:
    branches:
    - master
    paths:
    - '.github/**'

jobs:

  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get.outputs.version }}
    steps:
    - id: get
      run: |
        echo ::set-output name=version::${GITHUB_REF#refs/*/}

  build_and_publish_all_images:
    uses: itopia-inc/selkies-vdi/.github/workflows/build_and_publish_all_images.yaml@main
    with:
      image_version: ${{ jobs.get_version.outputs.version }}
