name: "Trigger: A release tag was pushed to the repo"

on:
  push:
    tags:
      - "v*"

env:
  github_token: ${{ secrets.GITHUB_TOKEN }}
  github_username: ${{ github.actor }}
  image_version_1: ${{ github.ref_name }}
  image_version_2: latest

jobs:
  app_proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: app-proxy
          image_source_directory: images/app-proxy
          image_version_1: $image_version_1
          image_version_2: $image_version_2

  app_streaming_bionic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          dockerfile: Dockerfile.bionic
          github_token: $github_token
          github_username: $github_username
          image_name: app-streaming
          image_source_directory: images/app-streaming
          image_version_1: $image_version_1
          image_version_2: $image_version_2
          image_version_suffix: -bionic

  app_streaming_buster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: app-streaming
          image_source_directory: images/app-streaming
          image_version_1: $image_version_1
          image_version_2: $image_version_2
          image_version_suffix: -buster

  app_streaming_focal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          dockerfile: Dockerfile.focal
          github_token: $github_token
          github_username: $github_username
          image_name: app-streaming
          image_source_directory: images/app-streaming
          image_version_1: $image_version_1
          image_version_2: $image_version_2
          image_version_suffix: -focal

  app_streaming_focal_cuda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          dockerfile: Dockerfile.focal-cuda
          github_token: $github_token
          github_username: $github_username
          image_name: app-streaming
          image_source_directory: images/app-streaming
          image_version_1: $image_version_1
          image_version_2: $image_version_2
          image_version_suffix: -focal-cuda

  desktop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: desktop
          image_source_directory: images/desktop
          image_version_1: $image_version_1
          image_version_2: $image_version_2

  pulseaudio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: pulseaudio
          image_source_directory: images/pulseaudio
          image_version_1: $image_version_1
          image_version_2: $image_version_2

  squid_proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: squid-proxy
          image_source_directory: images/squid-proxy
          image_version_1: $image_version_1
          image_version_2: $image_version_2

  tinyfilemanager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: tinyfilemanager
          image_source_directory: images/tinyfilemanager
          image_version_1: $image_version_1
          image_version_2: $image_version_2

  uinput_device_plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: uinput-device-plugin
          image_source_directory: images/uinput-device-plugin
          image_version_1: $image_version_1
          image_version_2: $image_version_2

  watchdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: watchdog
          image_source_directory: images/watchdog
          image_version_1: $image_version_1
          image_version_2: $image_version_2

  webrtc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: webrtc
          image_source_directory: images/webrtc
          image_version_1: $image_version_1
          image_version_2: $image_version_2

  xpra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: xpra
          image_source_directory: images/xpra
          image_version_1: $image_version_1
          image_version_2: $image_version_2

  xserver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & publish image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_token: $github_token
          github_username: $github_username
          image_name: xserver
          image_source_directory: images/xserver
          image_version_1: $image_version_1
          image_version_2: $image_version_2

  create_release:
    needs:
      - app_proxy
      - app_streaming_bionic
      - app_streaming_buster
      - app_streaming_focal
      - app_streaming_focal_cuda
      - desktop
      - pulseaudio
      - squid_proxy
      - tinyfilemanager
      - uinput_device_plugin
      - watchdog
      - webrtc
      - xpra
      - xserver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          release_name: Release $GITHUB_REF_NAME
          tag_name: $GITHUB_REF_NAME
