name: Publish release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  # Note: When modifying this job, copy modifications to all other workflows' image jobs.
  all_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: app-proxy
            source_directory: images/app-proxy

          - name: app-streaming
            version_suffix: -bionic
            dockerfile: Dockerfile.bionic
            source_directory: images/app-streaming

          - name: app-streaming
            version_suffix: -buster
            source_directory: images/app-streaming

          - name: app-streaming
            version_suffix: -focal
            dockerfile: Dockerfile.focal
            source_directory: images/app-streaming

          - name: app-streaming
            version_suffix: -focal-cuda
            dockerfile: Dockerfile.focal-cuda
            source_directory: images/app-streaming

          - name: desktop
            source_directory: images/desktop

          - name: pulseaudio
            source_directory: images/pulseaudio

          - name: squid-proxy
            source_directory: images/squid-proxy

          - name: tinyfilemanager
            source_directory: images/tinyfilemanager

          - name: uinput-device-plugin
            source_directory: images/uinput-device-plugin

          - name: watchdog
            source_directory: images/watchdog

          - name: webrtc
            source_directory: images/webrtc

          - name: xpra
            source_directory: images/xpra
            submodules: recursive

          - name: xserver
            source_directory: images/xserver

    name: ${{ matrix.name }}${{ matrix.version_suffix }} image build & publish
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: ${{ matrix.submodules }}

      - name: Build & publish ${{ matrix.name }} image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
          github_username: ${{ github.actor }}
          image_name: ${{ matrix.name }}
          image_source_directory: ${{ matrix.source_directory }}
          image_version_1: ${{ github.ref_name }}_1${{ matrix.version_suffix }}
          image_version_2: latest${{ matrix.version_suffix }}

  create_release:
    needs: all_images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          release_name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
